// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idnsjpmpuifvbidxfytl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkbnNqcG1wdWlmdmJpZHhmeXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTY5MjQsImV4cCI6MjA2NTUzMjkyNH0.1oljI78LnOKheEzaUUMwB1C0i2sI_CQmN_iDJlGizTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);